EX_OK = 0
EX_DATAERR = 65
EX_NOINPUT = 66
EX_SOFTWARE = 70
EX_CONFIG = 78

MAX_MARKDOWN_FILE_SIZE_BYTES = 1_048_576
MAX_YAML_BLOCK_SIZE_BYTES = 262_144
MAX_SARIF_MESSAGE_LENGTH = 20_000
MAX_ISSUES_PER_FILE = 200
DEFAULT_CLOCK_SKEW_SECONDS = 300

SARIF_VERSION = "2.1.0"
SARIF_SCHEMA_URL = "https://json.schemastore.org/sarif-2.1.0.json"

DEFAULT_CONFIG_PATH = ".incident-ci.yaml"
DEFAULT_SARIF_OUTPUT_PATH = "incident-ci.sarif"
